agent:
  backend_url: "http://192.168.56.1:8080/api/v1/telemetry"
  backend_auth_token_env: "SWITCHIFY_BACKEND_TOKEN"
  send_interval_seconds: 10
  max_queue_size: 1000
  timeout_seconds: 5
  test_hosts: 
       - "8.8.8.8"
       - "0.0.0.0"

primary_isp:
  name: "primary"
  interface: "enxfeb7f4ce3f04"
  test_hosts:
    - "1.1.1.1"
    - "8.8.8.8"
  icmp_threshold_ms: 120
  packet_loss_threshold_pct: 10
  fail_count: 3

backup_isp:
  name: "backup"
  interface: "enx664a11be0277"
  test_hosts:
    - "1.0.0.1"
    - "8.8.8.8"

logging:
  level: "debug"
  format: "json"

isp:
  primaryRouteCmd: "ip route replace default via 10.0.2.2 dev enp0s3"
  backupRouteCmd: "echo 'No backup isp configured'"

kafka:
   brokers:
          - 10.0.2.2:9094